# Generated by Django 5.1 on 2024-09-03 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orig_url", models.URLField()),
                (
                    "short_url",
                    models.CharField(
                        help_text="Must be exactly 7 Character long",
                        max_length=7,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(7),
                            django.core.validators.MinLengthValidator(7),
                        ],
                    ),
                ),
                ("visited", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
