# Generated by Django 5.1 on 2024-09-03 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiny_url", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="short_url",
            field=models.CharField(
                help_text="Must be exactly 7 Character long",
                max_length=7,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(7)],
            ),
        ),
    ]
